name: Deploy Quartz Site

on:
  push:
    branches:
      - deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Quartz Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install and Build Quartz
        run: |
          echo "Cloning Quartz repository..."
          git clone https://github.com/jackyzha0/quartz.git

          echo "Removing cloned quartz .git to avoid conflict..."
          rm -rf quartz/.git

          echo "Copying .git folder from root repo to quartz..."
          cp -r .git quartz/.git

          echo "Cloning content repo inside quartz/content to preserve git history..."
          rm -rf quartz/content
          git clone https://github.com/Wizziii/ravenpedia.git quartz/content

          echo "Copying config files from the repository root..."
          cp ./quartz.config.ts ./quartz/quartz.config.ts
          cp ./quartz.layout.ts ./quartz/quartz.layout.ts

          cd quartz
          echo "Installing dependencies..."
          npm install

          echo "Building site..."
          npx quartz build

          echo "Moving built files to destination..."
          mkdir -p ../_site
          mv ./public/* ../_site

      - name: Verify build folder contents
        run: |
          echo "Listing _site folder contents"
          ls -alh ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4